name: Install Dependencies
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2.4.0
      with:
        version: 8

    - run: pnpm install --frozen-lockfile
      shell: bash
