name: Install Dependencies
runs:
  using: composite
  steps:
    - run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6
      shell: bash
    - run: pnpm install --frozen-lockfile
      shell: bash
