name: Install Dependencies
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7

    - run: pnpm install --frozen-lockfile
      shell: bash
