name: Create Release
on:
  workflow_dispatch: {}

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: ./.github/actions/install

      - uses: ./.github/actions/verify

      - name: Create Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: 'false'

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
