name: Deployment
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy Dev
    runs-on: self-hosted
    concurrency: dev
    steps:
      - name: Install Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          lfs: true

      - uses: ./.github/actions/install

      - uses: ./.github/actions/verify

      - name: Setup Role Environment Variable
        run: echo DEV_ROLE_ARN=$DEV_ROLE_ARN >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ env.DEV_ROLE_ARN }}
          role-duration-seconds: 900
          role-session-name: DeployToDev

      - name: Deploy to Dev
        run: yarn workspace hacker-rank-review-aws infra:up
        shell: bash
