name: Deployment
on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Install Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Echo Dev Role
        run: echo ${{ env.DEV_ROLE_ARN }}

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: ./.github/actions/install

      - uses: ./.github/actions/verify

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ env.DEV_ROLE_ARN }}
          role-duration-seconds: 900
          role-session-name: DeployToDev

      - name: Deploy to Dev
        run: yarn workspace hacker-rank-review-aws infra:up
        shell: bash
