name: PR Checks
on:
  push:
    branches-ignore:
      - main

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-20.04
    steps:
      - name: Install Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: ./.github/actions/install

      - uses: ./.github/actions/verify
