name: PR Checks
on:
  push:
    branches-ignore:
      - main

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - uses: ./.github/actions/install

      - uses: ./.github/actions/verify
